### ISSUE TITLE
M3 - login/logout backend impletation

### ISSUE THREAD

**Issue by jedyang97** [YourTeamName/buzz-movie-selector#1]
Implement the backend of login/logout.

**Comment by ArkaneCow** [comment]
@jedyang97 @Nramanan6 - i assume you guys are working on login/logout which means working on user sessions. I found this online: http://developer.android.com/training/basics/data-storage/shared-preferences.html . it's mainly for storing application settings so i don't know if it's ideal for user session. I recommend keep looking for the "correct" way for user sessions. If you can't find any, sharedpreferences is a decent choice

**Comment by jedyang97** [comment]
Thank you, Jason! I will look for the best way to store the user credential status.

**Comment by Nramanan6** [comment]
Will continue looking into this as well

**Comment by ArkaneCow** [comment]
@Nramanan6 added credential validation in f28a1a1 however, we still need to have login update the application state
