### ISSUE TITLE
We don't need a toast each time we switch screen

### ISSUE THREAD

**Issue by jedyang97** [YourTeamName/buzz-movie-selector#13]
Currently, the login button and register button both make a toast when clicked. I don't think we need to do that. The screen switching will be faster if we cancel the toast.

**Comment by Nramanan6** [comment]
I assumed this was for testing purposes only

**Comment by Nramanan6** [comment]
I'm gonna remove all unnecessary toasts in my next commit

**Comment by jedyang97** [comment]
btw, you can add "close #..." in the pull request to automatically close the issue
