### ISSUE TITLE
Replace editor.clear() with editor.remove()

### ISSUE THREAD

**Issue by jedyang97** [YourTeamName/buzz-movie-selector#26]
For `saveState()` and  `logout()`, we shouldn't use [editor.clear()](https://github.com/YourTeamName/buzz-movie-selector/blob/jason/doTodos/app/src/main/java/edu/gatech/buzzmovieselector/SessionState.java#L81-L92) because this will actually throw all other saved preferences away. Using [remove()](http://developer.android.com/reference/android/content/SharedPreferences.Editor.html#remove(java.lang.String)) is probably a better idea for `logout`; and for `saveState()` I think we can just delete the `clear()` because we don't want other preferences to change.

**Comment by ArkaneCow** [comment]
I'm not 100% sure about this. I feel like if there was anything else stored in the session, for example lastWatchedMovie, that should not persist when the user logs out either. Maybe more appropriate would be to rename `logout()` to `endSession()`

**Comment by ArkaneCow** [comment]
Changed `login(User user, Context context)` to `startSession(User user, Context context)` and `logout(Context context)` to `endSession(Context context)` in 2456c26
