### ISSUE TITLE
Register Check Email Address

### ISSUE THREAD

**Issue by jeremyzhang12** [YourTeamName/buzz-movie-selector#29]
When we create account, the email address has never been checked if it already exits. I think we can add another hashMap under UserManger using user as key and email as value.

**Comment by ArkaneCow** [comment]
I agree - we should think about how to implement this though - add a new field to User or make a UserProfile class that is aggregated in user

**Comment by ArkaneCow** [comment]
According to our design, the login system does not require email addresses to be unique. I don't think we need to check if the email address is already in the system.
