### ISSUE TITLE
Fontend - Add user profile page

### ISSUE THREAD

**Issue by jedyang97** [YourTeamName/buzz-movie-selector#32]
We will need to add a "Profile" button in the drawer on the BMS screen. When user clicks onto that button, a non-editable profile page of that user will pop up. When user click "Edit" on that page, he will enter a editable profile page. On the editable page, there will be a "submit" button and "cancel" button, which will bring the user back to the non-editable profile page.

**Comment by jeremyzhang12** [comment]
The button has been added but we need to create some profile class and UI for next stage.

**Comment by ArkaneCow** [comment]
This has been implemented in #39 and is currently pending merge onto master.
